### ISSUE TITLE
model.predict called before model.train?

### ISSUE THREAD

**Issue by shanemcandrewai** [JoshVarty/AlphaZeroSimple#8]
Hi,

From the [code](https://github.com/JoshVarty/AlphaZeroSimple/blob/master/main.py), I see [trainer.learn()](https://github.com/JoshVarty/AlphaZeroSimple/blob/master/main.py#L26) calls [self.exceute_episode()](https://github.com/JoshVarty/AlphaZeroSimple/blob/master/trainer.py#L57) which in turn, calls [self.mcts.run](https://github.com/JoshVarty/AlphaZeroSimple/blob/master/trainer.py#L28) when then calls [model.predict(state)](https://github.com/JoshVarty/AlphaZeroSimple/blob/master/monte_carlo_tree_search.py#L102). Is it intentional to predict the policy and value before training the network?

**Comment by JoshVarty** [comment]
Yes, it's intentional to use the police/value networks before they've actually been trained.

Initially they are randomly generated (and probably don't make good predictions). However, we use these random police/value networks to play a bunch of games and we keep track of who won/lost in each game. We use these games as a temporary dataset and train each random policy/value network to be slightly better.

We repeat this process many times. Although we started with a random policy/value network, over time we have improved it such that it's no longer random and actually starts to accurately predict moves and values.
